#影视动态刷
query postWithMoviesQuery {
    postWithMovies {
         id
    spider {
        id
    }
    content
    description
    status
    liked
    count_likes
    count_comments
    review_id
    review_day
    is_ad
    created_at
    current_episode
    user {
        id
        name
        avatar
        followed_status
        gender
        age
        introduction
    }
    images {
        id
        url
        width
        height
    }
    video {
        id
        url
        cover
        dynamic_cover
        duration
        width
        height
    }
    movies {
        id
        name
        introduction
        cover
    }
        collections {
             id
    logo
    name
    description
    count_articles
    count_follows
    count_posts
    count_views
    updated_to_episode
    followed
    user {
        id
        name
        avatar
    }
    movies {
        id
        name
        introduction
        cover
    }
        }
    }
}