# 电影推荐
query recommendMovieQuery{
  recommendMovie{
    id
    name
    introduction
    cover
    year
    type
    style
    actors
    count_series
    lang
    producer
    region
    score
    data{
      name
      url
    }
  }
}