

# 搜索影视
query searchMoviesQuery($keyword: String!, $first: Int, $page: Int) {
    searchMovie(keyword: $keyword, first: $first, page: $page) {
        paginatorInfo {
            currentPage
            hasMorePages
        }
        data {                
        id
        name
        introduction
        cover
        }
        }
    }
