# 观看历史记录
query showMovieHistoryQuery($first: Int, $page: Int) {
    showMovieHistory(first: $first, page: $page) {
        paginatorInfo {
            hasMorePages
            currentPage
        }
        data {
            id
            last_watch_time
            movie {
                id
                name
                introduction
                cover            
        }
        }
    }
}
